# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_location', models.CharField(default=b'', max_length=1000)),
                ('court_id', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('image_src', models.CharField(default=b'', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('value', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avbl.Court')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='DateTimeValue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
