# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_location', models.CharField(max_length=1000)),
                ('court_id', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
