# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avbl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='image_src',
        ),
    ]
