# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avbl', '0002_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
