# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avbl', '0007_auto_20170526_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=9)),
                ('time', models.CharField(max_length=9)),
                ('date_time', models.DateTimeField()),
                ('value', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avbl.Court')),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='court',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
